pub mod instruction;
pub mod commands;

use std::collections::HashMap;
use regex::Regex;

pub fn assemble(source_text: &str) -> Result<(Vec<u8>, Vec<u32>), String> {
    let mut rom: Vec<u8> = Vec::new();
    let mut errors = String::new();
    
    let re_label = Regex::new(r"(?i)^([A-Z0-9_]+):$").unwrap();
    let handlers = commands::get_all_handlers();

    let mut labels: HashMap<String, u16> = HashMap::new();
    let mut current_addr: u16 = 0;
    let mut parsed_lines = Vec::new();

    // --- PASS 1: Calculate Sizes ---
    for (i, line) in source_text.lines().enumerate() {
        let clean = line.split(';').next().unwrap_or("").trim().to_uppercase();
        if clean.is_empty() { continue; }

        if let Some(caps) = re_label.captures(&clean) {
            labels.insert(caps[1].to_uppercase(), current_addr);
        } else {
            // Ask each file in the folder if they recognize the command
            let mut matched_size = 1; // Default fallback
            for handler in &handlers {
                if let Some(size) = handler.check_size(&clean) {
                    matched_size = size;
                    break;
                }
            }
            parsed_lines.push((i + 1, current_addr, clean));
            current_addr += matched_size;
        }
    }

    let mut pc_to_line: Vec<u32> = Vec::new();

    // --- PASS 2: Generate Hex ---
    for (line_num, addr, clean_line) in parsed_lines {
        let start_len = rom.len();
        let mut handled = false;

        // Pass the line to each handler in the folder
        for handler in &handlers {
            if let Some(result) = handler.generate(&clean_line, addr, &labels) {
                handled = true;
                match result {
                    Ok(mut bytes) => rom.append(&mut bytes),
                    Err(e) => errors.push_str(&format!("Line {}: {}\n", line_num, e)),
                }
                break; // Stop asking other handlers, this one did the job
            }
        }

        if !handled {
            errors.push_str(&format!("Line {}: Unrecognized instruction '{}'\n", line_num, clean_line));
        }

        // Map the generated bytes to the line number for the UI Highlight
        for _ in 0..(rom.len() - start_len) {
            pc_to_line.push(line_num as u32);
        }
    }

    if !errors.is_empty() { Err(errors) } else { Ok((rom, pc_to_line)) }
}